### ISSUE TITLE
Bug: Init function params are always overriden with undefined environment variables 

### ISSUE THREAD

**Issue by calderaro** [kinde-oss/management-api-js#10]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Hi, I’m currently trying to integrate the management-api-js on a project to load the user's profile data.

In my code im doing something similar to this:

```
import { Users, init } from "@kinde/management-api-js";

init({
    kindeDomain: "https://myurl.kinde.com",
    clientId: "myclientId",
    clientSecret: "myclientsecret",
});


export async function GET() {
  const { users } = await Users.getUsers();
  return NextResponse.json({ message: "success", users });
};
```

And i get this error: ```Error: kindeDomain or env KINDE_DOMAIN is not set```

i took a look at the init function code and i think the problem is the _merge function that always overrides the init function params with the environment variables even if those don't exist.

```
function _merge(target: object = {}, ...objects: object[]): object {
  return Object.assign(target, ...objects.filter(Boolean));
}

console.log(_merge({ a: 1 }, { b: 2 }, { b: undefined }));

//logs: { a: 1, b: undefined }
```

### Library URL

https://github.com/kinde-oss/management-api-js

### Library version

0.6.0

### Operating system(s)

macOS

### Operating system version(s)

Somona

**Comment by DanielRivers** [comment]
Thanks for raising. I will get this resolved.
