### ISSUE TITLE
Bug: getRolePermission  ts type do not match with the response 

### ISSUE THREAD

**Issue by alexbitar98** [kinde-oss/management-api-js#20]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

when trying to use  Roles.getRolePermission
the retrurned type is roles_permission_response
but this do not match with the data retuned throigh the api
`{
  code: 'OK',
  message: 'Success',
  next_token: 'eg id',
  permissions: [
    {
      id: 'eg id',
      key: 'test',
      name: 'test,
      description: ''
    },`

### Library URL

https://github.com/kinde-oss/management-api-js

### Library version

^0.8.0

### Operating system(s)

Windows

### Operating system version(s)

windows 11

**Comment by DanielRivers** [comment]
This has been resolved in 0.10
