### ISSUE TITLE
Documentation issue: permission_id has wrong type

### ISSUE THREAD

**Issue by ABoyd002** [kinde-oss/management-api-js#24]
### Prerequisites

- [X] I have searched the repository’s issues and the [Kinde community](https://thekindecommunity.slack.com/archives/C057M2BQ6LV) to ensure my documentation issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### How can we improve the docs or what is missing?

Under [List Permissions](https://kinde.com/api/docs/?http#list-permissions) is states that permission_id is of type string but on [Update Permission](https://kinde.com/api/docs/?http#update-permission) it is of type integer.

The other pages all seem to show the type of permission_id as a string.

### Provide extra context, such as what you were trying to do and your requirements

Trying to add the day to day usage of Kinde directly into our SaaS product to save us having to do things directly within the management portal.

### If the docs page already exists, please provide a link

https://kinde.com/api/docs/?http#update-permission

**Comment by DanielRivers** [comment]
Hi @ABoyd002,

Thanks for pointing this out, I have raised a fix for the API docs.  Once deployed I will get this fixed up on this package.

**Comment by ABoyd002** [comment]
Hey @DanielRivers,

Cheers for getting this looked at so quickly.

**Comment by DanielRivers** [comment]
@ABoyd002, our main API schema has been updated, I will get this fixed up today, thank you for your patience.

**Comment by DanielRivers** [comment]
@ABoyd002 Apologies for the delays getting this released. There was a change made to the API which would result in a breaking change in this package.  We are looking to mitigate that at the moment.
